---
title: "Chapter 5: Data Transformation, Continued"
output: 
  html_document: 
    keep_md: yes
---

##5.6 Grouped summaries with `summarise()`


###5.6.7 Exercises

**1. Brainstorm at least 5 different ways to assess the typical delay characteristics of a group of flights. Consider the following scenarios:**  

* A flight is 15 minutes early 50% of the time, and 15 minutes late 50% of the time.
* A flight is always 10 minutes late.  
* A flight is 30 minutes early 50% of the time, and 30 minutes late 50% of the time.  
* 99% of the time a flight is on time. 1% of the time it's 2 hours late.  

**Which is more important, arrival delay or departure delay?**  

**2. Come up with another approach that will give you the same outpt as `not_cancelled %>% count(tailnum, wt = distance)` without using `count()`.**

**3. Our definition of cancelled flights `is.na(dep_delay) | is.na(arr_delay)` is slightly suboptimal. Why? Which is the most important column?**  

**4. Look at the number of cancelled flights per day. Is there a pattern? Is the proportion of cancelled flights related to the average delay?**

**5. Which carrier has the worst delays? Challenge: can you disentangle the effects of bad airports vs. bad carriers? Why/why not? (Hint: think about `flights %>% group_by(carrier, dest) %>% summarise(n())`.**

**6. What does the `sort` argument to `count()` do. When might you use it?**

##5.7 Grouped mutates and filters  

###5.7.1 Exercises  

**1. Refer back to the lists of useful mutate and filtering functions. Describe how each operation changes when you combine it with grouping.**  

**2. Which plane (`tailnum`) has the worst on-time record?**  

**3. What time of day should you fly if you want to avoid delays as much as possible?**

**4. For each destination, compute the total minutes of delay. For each, flight, compute the proportion of the total delay for its destination.**

**5. Delays are typically temporally correlated: even once the problem that caused the initial delay has been resolved, later flights are delayed to allow earlier flights to leave. Using `lag()` explore how the delay of a flight is related to the delay of the immediately preceding flight.**  

**6. Look at each destination. Can you find flights that are suspiciously fast? (i.e. flights that represent a potential data entry error). Compute the air time a flight relative to the shortest flight to that destination. Which flights were most delayed in the air?**  

**7. Find all destinations that are flown by at least two carriers. Use that information to rank the carriers.**  

**8. For each plane, count the number of flights before the first delay of greater than 1 hour.**  

#Chapter 6: Workflow: scripts  

###6.3 Practice  

**1. Go to the RStudio Tips twitter account, https://twitter.com/rstudiotips and find one tip that looks interesting. Practice using it!**

**2. What other common mistakes will RStudio diagnostics report? Read https://support.rstudio.com/hc/en-us/articles/205753617-Code-Diagnostics to find out.**
